server:
  port: 80
spring:
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates
    cache: false
    allow-request-override: true
    allow-session-override: true
    check-template-location: true
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usual?characterEncoding=utf8&useSSL=false&useUnicode=true&serverTimezone=UTC
    hikari:
      validation-timeout: 3000
      connection-timeout: 60000
      idle-timeout: 60000
      max-lifetime: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #  mybatis主配置文件所在路径
  type-aliases-package: com.yun.usual.entity   #  定义所有操作类的别名所在包
  mapper-locations:                                     #  所有的mapper映射文件
    - classpath:mybatis/mapper/*.xml
